In [220]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/winequality-red.csv')
print(df)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

In [221]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [222]:
df.loc[df["quality"] >= 7, "good quality"] = "1"
df.loc[df["quality"] < 7, "good quality"] = "0"
df = df.drop('quality', axis=1)
df.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol good quality  
0      9.4            0  
1      9.8            0  
2      9.8            0  
3      9.8            0  
4      9.4            0

In [223]:
#Data pre-processing

In [224]:
x = df[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']].values

In [225]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [226]:
y = df[['good quality']].values
y

array([['0'],
       ['0'],
       ['0'],
       ...,
       ['0'],
       ['0'],
       ['0']], dtype=object)

In [227]:
print(df.isnull().sum())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
good quality            0
dtype: int64


In [228]:
from sklearn.model_selection import train_test_split

In [229]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [230]:
x_train

array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

In [231]:
x_test

array([[10.8  ,  0.47 ,  0.43 , ...,  3.17 ,  0.76 , 10.8  ],
       [ 8.1  ,  0.82 ,  0.   , ...,  3.36 ,  0.53 ,  9.6  ],
       [ 9.1  ,  0.29 ,  0.33 , ...,  3.26 ,  0.84 , 11.7  ],
       ...,
       [ 9.1  ,  0.34 ,  0.42 , ...,  3.18 ,  0.55 , 11.4  ],
       [ 9.1  ,  0.765,  0.04 , ...,  3.29 ,  0.54 ,  9.7  ],
       [ 8.2  ,  0.32 ,  0.42 , ...,  3.27 ,  0.55 , 12.3  ]])

In [232]:
y_train

array([['0'],
       ['0'],
       ['0'],
       ...,
       ['0'],
       ['0'],
       ['0']], dtype=object)

In [233]:
y_test

array([['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
      

In [234]:
from sklearn.preprocessing import StandardScaler

In [235]:
sc_x = StandardScaler()

In [236]:
x_train = sc_x.fit_transform(x_train)

In [237]:
x_test = sc_x.transform(x_test)

In [238]:
x_train

array([[ 0.90103398,  0.05480282,  0.9094138 , ...,  0.52091013,
        -0.22358408, -0.95579434],
       [ 1.41998736, -1.47967601,  0.9094138 , ..., -1.16841553,
        -0.68130963, -0.76727388],
       [ 0.90103398, -0.98645067,  1.4208416 , ..., -0.3237527 ,
         0.74908272,  0.17532846],
       ...,
       [-0.25219574,  0.21921126,  0.19341488, ..., -0.12883051,
         0.17692578, -0.86153411],
       [ 2.68854005, -0.32881689,  1.11398492, ..., -0.06385645,
         0.11971008,  2.15479335],
       [ 0.84337249,  2.46612668,  0.24455766, ..., -0.38872677,
        -1.0246038 , -0.95579434]])

In [239]:
x_test

array([[ 1.41998736, -0.32881689,  0.80712824, ..., -0.90851928,
         0.57743564,  0.36384892],
       [-0.13687277,  1.58928164, -1.39201131, ...,  0.32598793,
        -0.73852533, -0.76727388],
       [ 0.43974209, -1.31526756,  0.29570044, ..., -0.3237527 ,
         1.03516119,  1.21219102],
       ...,
       [ 0.43974209, -1.04125349,  0.75598546, ..., -0.84354521,
        -0.62409394,  0.92941032],
       [ 0.43974209,  1.28786615, -1.18744019, ..., -0.12883051,
        -0.68130963, -0.67301364],
       [-0.07921128, -1.15085912,  0.75598546, ..., -0.25877864,
        -0.62409394,  1.77775242]])

In [240]:
#classification algorithms
#Logistic Regression

In [241]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [242]:
#Making the logistic regression mode

In [243]:
logistic_model = LogisticRegression()

In [244]:
#Training the model

In [245]:
logistic_model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [246]:
#Predicting the labels of the test data

In [247]:
y_pred = logistic_model.predict(x_test)

In [248]:
#Evaluating scores

In [249]:
accuracy = accuracy_score(y_test,y_pred)*100

confusion_mat = confusion_matrix(y_test,y_pred)

In [250]:
#Printing the results

In [251]:
print("Accuracy is",accuracy)
print("Confusion Matrix")
print(confusion_mat)

Accuracy is 90.3125
Confusion Matrix
[[277  13]
 [ 18  12]]


In [252]:
#K-Nearest Neighbors
import numpy as nm
import matplotlib.pyplot as mtp

In [253]:
#Fitting K-NN classifier to the training set

In [254]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [255]:
#Predicting the test set result
y_pred= classifier.predict(x_test)
y_pred

array(['0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1',
       '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0

In [256]:
#Creating the Confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[276,  14],
       [ 13,  17]])

In [257]:
#Decision Trees Classifier

In [258]:
(x,y)

(array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
        [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
        [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
        ...,
        [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
        [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
        [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]]),
 array([['0'],
        ['0'],
        ['0'],
        ...,
        ['0'],
        ['0'],
        ['0']], dtype=object))

In [259]:
x_train.shape

(1279, 11)

In [260]:
x_test.shape

(320, 11)

In [261]:
from sklearn.tree import DecisionTreeClassifier

In [262]:
model = DecisionTreeClassifier()

In [263]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [264]:
y_pred =model.predict(x_test)

In [265]:
y_test

array([['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
      

In [266]:
from sklearn import metrics

In [267]:
print(metrics.accuracy_score(y_test,y_pred))

0.903125


In [268]:
#Random Forest Classifier

In [269]:
from sklearn.ensemble import RandomForestClassifier

In [270]:
clf = RandomForestClassifier(n_estimators=10,random_state=0,n_jobs=-1)

In [271]:
clf

RandomForestClassifier(n_estimators=10, n_jobs=-1, random_state=0)

In [272]:
clf.fit(x_train,y_train)
clf.score(x_test,y_test)

<ipython-input-272-b82a7cef201b>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(x_train,y_train)


0.921875

In [273]:
#Logistic Regression from Scratch

In [274]:
df.head()


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol good quality  
0      9.4            0  
1      9.8            0  
2      9.8            0  
3      9.8            0  
4      9.4            0

In [275]:
(x,y)

(array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
        [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
        [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
        ...,
        [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
        [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
        [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]]),
 array([['0'],
        ['0'],
        ['0'],
        ...,
        ['0'],
        ['0'],
        ['0']], dtype=object))

In [276]:
x = np.array(x)
y = np.array(y)

In [277]:
x.shape

(1599, 11)

In [278]:
y.shape

(1599, 1)

In [279]:
x = np.c_[np.ones(len(x)),x]

In [280]:
x.shape

(1599, 12)

In [281]:
x = x.T

In [282]:
x.shape

(12, 1599)

In [283]:
#Compute hypothesis(sigmoid function) implementation

In [284]:
def compute_hypothesis(params,x):
  z=np.matmul(params.T,x)
  predictions = 1/(1+np.exp(-z))
  return predictions

In [285]:
#predict classes

In [286]:
def predict_classes(predictions):
  predicted_classes =np.zeros(len(predictions))
  predicted_classes[np.where(predictions>=0.5)] = 1
  return predicted_classes

In [287]:
#Calculate accuracies

In [288]:
def calculate_accuracy(class_predictions,actual):
  accuracy = (sum(class_predictions==actual)/len(actual))*100
  return accuracy

In [289]:
#compute cost(log loss/cross entrophy loss function) implementaions

In [290]:
def compute_cost(predictions,actual):
  m = len(actual)
  log_of_predictions = np.log(predictions)
  log_of_oneMinusPredictions = np.log(1-predictions)
  cost = -(1/m)*np.sum(((actual*log_of_predictions)+((1-actual)*(log_of_oneMinusPredictions))))
  return cost

In [291]:
#gradient descent implementation

In [292]:
def gradient_descent(x,y,learning_rate,iterations):
  actual = y
  costs = []
  accuracies = []
  params = np.zeros(x.shape[0])
  m = len(actual)
  for i in range(iterations):
    predictions = compute_hypothesis(params,x)
    class_predictions = predict_classes(predictions)
    accuracies.append(calculate_accuracy(class_predictions,actual))
    costs.append(compute_cost(predictions,actual))
    errors = predictions - actual
    gradients = (1/m)*np.matmul(x,errors)
    params = params - (learning_rate*gradients)
    return params, costs, accuracies

In [293]:
#verifications

In [294]:
params = np.zeros(x.shape[0])
predictions = compute_hypothesis(params,x)


In [295]:
len(predictions)

1599

In [300]:
actual = y
m = len(actual)
log_of_predictions = np.log(predictions)
log_of_oneMinusPredictions = np.log(1-predictions)
cost = -(1/m)*np.sum(((actual*log_of_predictions) + ((1-actual)*(log_of_oneMinusPredictions))))

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
cost

In [301]:
learning_rate = 0.00001
errors = predictions - actual
gradients = (1/m)*np.matmul(x,errors)
params = params -(learning_rate*gradients)

TypeError: unsupported operand type(s) for -: 'float' and 'str'

In [302]:
len(gradients)

NameError: name 'gradients' is not defined