# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [4]:
def isValid(A,B):
  if len(A[0]) != len(B):
        return "not valid"
  
  else :
      return "valid"


##### (ii) Using loops (without using numpy)

In [5]:
def matrix_multiply(A,B):
  final = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

  for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                final[i][j] += A[i][k] * B[k][j]

  return final


##### (iii) Using numpy

In [8]:
def matrix_multiply_2(A,B):
  result = np.dot(A, B)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [9]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

NameError: name 'np' is not defined

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [11]:
def mean(x):
  return sum(x)/len(x)

In [12]:
def standard_deviation(x):
  sq_diff = [(a - mean) ** 2 for a in x]
  variance = sum(sq_diff) / len(x)
  std_dev = variance ** 0.5
  return std_dev


In [13]:
def zscore_normalisation(x):
  mean_value = mean(x)
  std_dev_value = standard_deviation(x)

  normalized_data = [(a - mean_value) / std_dev_value for a in x]

  return normalized_data

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [17]:
def zscore_normalisation_2(x):
  mean_value = np.mean(x)
  std_dev_value = np.std(x)

  normalized_data = (x - mean_value) / std_dev_value

  return normalized_data


##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [20]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
normalized_data = zscore_normalisation(x)
print(f"Result without using numpy: {normalized_data}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

TypeError: unsupported operand type(s) for -: 'int' and 'function'

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [21]:
def sigmoidfn(x):
  return 1 / (1 + np.exp(-x))

##### (ii) Write a fn to implement derivative of sigmoid fn

In [22]:
def derivative(x):
  sigmoid_x = sigmoidfn(x)
  return sigmoid_x * (1 - sigmoid_x)

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [23]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

NameError: name 'np' is not defined

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [38]:
column_names = ['Pressure', 'liq_sat', 'vap_sat', 'property']

df = pd.read_csv(superheated_vapor_properties.csv , header=None, names=column_names)

print(df.head())

NameError: name 'pd' is not defined

### Display the shape of data frame


In [28]:
print(df.shape)

NameError: name 'df' is not defined

### Return an array containing names of all the columns

In [29]:
column_names_array = df.columns.to_numpy()

print(column_names_array)

NameError: name 'df' is not defined

### Display the number of null values in each column of the dataframe



In [30]:
null_counts = df.isnull().sum()

print(null_counts)

NameError: name 'df' is not defined

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [31]:
df['Combined'] = df['Property'] + ' at ' + df['Pressure'].astype(str) + ' kPa'

print(df.loc[(df['Pressure'] == 75) & (df['Temperature'] == 573), 'Combined'].values[0])

print(df.loc[(df['Temperature'] == 493) & (df['Pressure'] == 250), 'Combined'].values[0])

NameError: name 'df' is not defined

### Find out the column with the highest number of missing values

In [32]:
column_with_most_nulls = df.isnull().sum().idxmax()

print(f"The column with the highest number of missing values is: {column_with_most_nulls}")

NameError: name 'df' is not defined

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [33]:
saturated_liquid_df = df[df['Property'] == 'Sat. Liq.']
average_enthalpy = saturated_liquid_df['Enthalpy'].mean()

print(f"The average enthalpy of Sat. Liq. at all pressures is: {average_enthalpy}")

NameError: name 'df' is not defined

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [36]:
V_data = df[df['Property'] == 'Superheated Vapor']['SpecificVolume']
U_data = df[df['Property'] == 'Superheated Vapor']['SpecificInternalEnergy']
H_data = df[df['Property'] == 'Superheated Vapor']['SpecificEnthalpy']
S_data = df[df['Property'] == 'Superheated Vapor']['SpecificEntropy']

print("Specific Volume Data:")
print(V_data.head())

print("\nSpecific Internal Energy Data:")
print(U_data.head())

print("\nSpecific Enthalpy Data:")
print(H_data.head())

print("\nSpecific Entropy Data:")
print(S_data.head())

NameError: name 'df' is not defined

# Section 3: Plotting with Matplotlib

### Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [39]:
saturated_liquid_data = df[df['Property'] == 'Sat. Liq.']

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(12, 10))

axes[0, 0].plot(saturated_liquid_data['Pressure'], saturated_liquid_data['SpecificVolume'], marker='o', linestyle='-', color='b')
axes[0, 0].set_title('Specific Volume vs Pressure')
axes[0, 0].set_xlabel('Pressure (kPa)')
axes[0, 0].set_ylabel('Specific Volume')
axes[0, 0].grid(True)

axes[0, 1].plot(saturated_liquid_data['Pressure'], saturated_liquid_data['SpecificInternalEnergy'], marker='o', linestyle='-', color='r')
axes[0, 1].set_title('Specific Internal Energy vs Pressure')
axes[0, 1].set_xlabel('Pressure (kPa)')
axes[0, 1].set_ylabel('Specific Internal Energy')
axes[0, 1].grid(True)

axes[1, 0].plot(saturated_liquid_data['Pressure'], saturated_liquid_data['SpecificEnthalpy'], marker='o', linestyle='-', color='g')
axes[1, 0].set_title('Specific Enthalpy vs Pressure')
axes[1, 0].set_xlabel('Pressure (kPa)')
axes[1, 0].set_ylabel('Specific Enthalpy')
axes[1, 0].grid(True)

axes[1, 1].plot(saturated_liquid_data['Pressure'], saturated_liquid_data['SpecificEntropy'], marker='o', linestyle='-', color='purple')
axes[1, 1].set_title('Specific Entropy vs Pressure')
axes[1, 1].set_xlabel('Pressure (kPa)')
axes[1, 1].set_ylabel('Specific Entropy')
axes[1, 1].grid(True)

plt.tight_layout()

plt.show()


NameError: name 'df' is not defined

### Plot the same for saturated vapor.

In [ ]:
saturated_vapor_data = df[df['Property'] == 'Sat. Vap.']

fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(12, 10))

axes[0, 0].plot(saturated_vapor_data['Pressure'], saturated_vapor_data['SpecificVolume'], marker='o', linestyle='-', color='b')
axes[0, 0].set_title('Specific Volume vs Pressure')
axes[0, 0].set_xlabel('Pressure (kPa)')
axes[0, 0].set_ylabel('Specific Volume')
axes[0, 0].grid(True)

axes[0, 1].plot(saturated_vapor_data['Pressure'], saturated_vapor_data['SpecificInternalEnergy'], marker='o', linestyle='-', color='r')
axes[0, 1].set_title('Specific Internal Energy vs Pressure')
axes[0, 1].set_xlabel('Pressure (kPa)')
axes[0, 1].set_ylabel('Specific Internal Energy')
axes[0, 1].grid(True)

axes[1, 0].plot(saturated_vapor_data['Pressure'], saturated_vapor_data['SpecificEnthalpy'], marker='o', linestyle='-', color='g')
axes[1, 0].set_title('Specific Enthalpy vs Pressure')
axes[1, 0].set_xlabel('Pressure (kPa)')
axes[1, 0].set_ylabel('Specific Enthalpy')
axes[1, 0].grid(True)

axes[1, 1].plot(saturated_vapor_data['Pressure'], saturated_vapor_data['SpecificEntropy'], marker='o', linestyle='-', color='purple')
axes[1, 1].set_title('Specific Entropy vs Pressure')
axes[1, 1].set_xlabel('Pressure (kPa)')
axes[1, 1].set_ylabel('Specific Entropy')
axes[1, 1].grid(True)

plt.tight_layout()

plt.show()

### Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
saturated_liquid_data = df[(df['Property'] == 'Sat. Liq.') & (df['Pressure'] >= 300) & (df['Pressure'] <= 1500)]

plt.plot(saturated_liquid_data['Pressure'], saturated_liquid_data['SpecificVolume'], marker='o', linestyle='-', color='b')
plt.title('Specific Volume of Saturated Liquid vs Pressure')
plt.xlabel('Pressure (kPa)')
plt.ylabel('Specific Volume')
plt.grid(True)

plt.show()


# Section 4 : Conclusion

*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*