# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [1]:
 import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'numpy'

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:

  def isValid(A,B):
    # Check if the number of columns in the first matrix is equal to the number of rows in the second matrix
    return len(A[0]) == len(B)

# Example usage:
A = [[5,7,9],
           [10,11,12]]

B = [[9,7],
           [10,11],
           [23,5]]

if isValid(A,B):
    result = [[sum(a * b for a, b in zip(row1, col2)) for col2 in zip(*B)] for row1 in A]
    print("Matrix multiplication is valid. Resultant matrix:")
    for row in result:
        print(row)
else:
    print("Matrix multiplication is not valid.")

##### (ii) Using loops (without using numpy)

In [ ]:

def matrix_multiply(A, B):
    # Get the dimensions of the matrices
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    # Check if the matrices can be multiplied
    if cols_A != rows_B:
        raise ValueError("Matrices cannot be multiplied. Inner dimensions must match.")

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform matrix multiplication using nested loops
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

##### (iii) Using numpy

In [ ]:
import numpy as np

def matrix_multiply_2(A, B):
    # Convert input matrices to NumPy arrays
    A = np.array(A)
    B = np.array(B)

    # Perform matrix multiplication using NumPy's dot function
    result_matrix = np.dot(A, B)

    # Alternatively, you can use the @ operator for matrix multiplication in Python 3.5 and above
    # result_matrix = A @ B

    return result_matrix
  

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [2]:
def mean(x):
 x = [1, 2, 3, 4, 5]

 mean = sum(x) / len(x)

 print("Mean:", mean)

In [3]:
def standard_deviation(x):
    # Calculate mean
    mean = sum(x) / len(x)

    # Calculate squared differences from the mean
    squared_diff = [(num - mean) ** 2 for num in x]

    # Calculate variance
    variance = sum(squared_diff) / len(x)

    # Calculate standard deviation
    std_deviation = variance ** 0.5

    print("Standard Deviation:", std_deviation)

# Example usage:
numbers = [1, 2, 3, 4, 5]
standard_deviation(numbers)


Standard Deviation: 1.4142135623730951


In [5]:
def zscore_normalisation(x):
    # Calculate mean
    mean = sum(x) / len(x)

    # Calculate standard deviation
    variance = sum((num - mean) ** 2 for num in x) / len(x)
    std_deviation = variance ** 0.5

    # Calculate z-scores for each element
    z_scores = [(num - mean) / std_deviation for num in x]

    return z_scores

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [8]:
import numpy as np

def zscore_normalisation_2(x):
    # Calculate mean and standard deviation using NumPy
    mean = np.mean(x)
    std_deviation = np.std(x)

    # Calculate z-scores for each element
    z_scores = (x - mean) / std_deviation

    return z_scores

ModuleNotFoundError: No module named 'numpy'

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
import numpy as np

def sigmoidfn(x):
    return 1 / (1 + np.exp(-x))

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
import numpy as np

def derivative(x):
    s_x = sigmoid(x)
    return s_x * (1 - s_x)


##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [ ]:
#your code here

### Display the shape of data frame


In [ ]:
#your code here

### Return an array containing names of all the columns

In [ ]:
#your code here

### Display the number of null values in each column of the dataframe



In [ ]:
#your code here

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
#your code here

### Find out the column with the highest number of missing values

In [ ]:
#your code here

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
#your code here

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here

# Section 3: Plotting with Matplotlib

### Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Example data or functions for the properties
pressure_range = np.linspace(300, 1500, 100)  # Pressure range from 300 kPa to 1500 kPa

# Function to calculate saturated liquid properties 
def saturated_liquid_properties(p):
    specific_volume = np.ones_like(p) 
    specific_internal_energy = np.ones_like(p)  
    specific_enthalpy = np.ones_like(p)  
    specific_entropy = np.ones_like(p) 
    return specific_volume, specific_internal_energy, specific_enthalpy, specific_entropy

# Create subplots
fig, axs = plt.subplots(2, 2, figsize=(12, 10))
fig.suptitle('Saturated Liquid Properties vs Pressure', fontsize=16)

# Plot 1: Specific Volume vs Pressure
axs[0, 0].plot(pressure_range, saturated_liquid_properties(pressure_range)[0], marker='o')
axs[0, 0].set_title('Specific Volume')
axs[0, 0].set_xlabel('Pressure (kPa)')
axs[0, 0].set_ylabel('Specific Volume (m³/kg)')

# Plot 2: Specific Internal Energy vs Pressure
axs[0, 1].plot(pressure_range, saturated_liquid_properties(pressure_range)[1], marker='o')
axs[0, 1].set_title('Specific Internal Energy')
axs[0, 1].set_xlabel('Pressure (kPa)')
axs[0, 1].set_ylabel('Specific Internal Energy (kJ/kg)')

# Plot 3: Specific Enthalpy vs Pressure
axs[1, 0].plot(pressure_range, saturated_liquid_properties(pressure_range)[2], marker='o')
axs[1, 0].set_title('Specific Enthalpy')
axs[1, 0].set_xlabel('Pressure (kPa)')
axs[1, 0].set_ylabel('Specific Enthalpy (kJ/kg)')

# Plot 4: Specific Entropy vs Pressure
axs[1, 1].plot(pressure_range, saturated_liquid_properties(pressure_range)[3], marker='o')
axs[1, 1].set_title('Specific Entropy')
axs[1, 1].set_xlabel('Pressure (kPa)')
axs[1, 1].set_ylabel('Specific Entropy (kJ/(kg*K))')

plt.tight_layout(rect=[0, 0, 1, 0.96])  
plt.show()

### Plot the same for saturated vapor.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Example data or functions for the properties
pressure_range = np.linspace(300, 1500, 100)  # Pressure range from 300 kPa to 1500 kPa

# Function to calculate saturated vapor properties
def saturated_vapor_properties(p):
    specific_volume = np.ones_like(p)  
    specific_internal_energy = np.ones_like(p) 
    specific_enthalpy = np.ones_like(p)  
    specific_entropy = np.ones_like(p)  
    return specific_volume, specific_internal_energy, specific_enthalpy, specific_entropy

# Create subplots
fig, axs = plt.subplots(2, 2, figsize=(12, 10))
fig.suptitle('Saturated Vapor Properties vs Pressure', fontsize=16)

# Plot 1: Specific Volume vs Pressure
axs[0, 0].plot(pressure_range, saturated_vapor_properties(pressure_range)[0], marker='o')
axs[0, 0].set_title('Specific Volume')
axs[0, 0].set_xlabel('Pressure (kPa)')
axs[0, 0].set_ylabel('Specific Volume (m³/kg)')

# Plot 2: Specific Internal Energy vs Pressure
axs[0, 1].plot(pressure_range, saturated_vapor_properties(pressure_range)[1], marker='o')
axs[0, 1].set_title('Specific Internal Energy')
axs[0, 1].set_xlabel('Pressure (kPa)')
axs[0, 1].set_ylabel('Specific Internal Energy (kJ/kg)')

# Plot 3: Specific Enthalpy vs Pressure
axs[1, 0].plot(pressure_range, saturated_vapor_properties(pressure_range)[2], marker='o')
axs[1, 0].set_title('Specific Enthalpy')
axs[1, 0].set_xlabel('Pressure (kPa)')
axs[1, 0].set_ylabel('Specific Enthalpy (kJ/kg)')

# Plot 4: Specific Entropy vs Pressure
axs[1, 1].plot(pressure_range, saturated_vapor_properties(pressure_range)[3], marker='o')
axs[1, 1].set_title('Specific Entropy')
axs[1, 1].set_xlabel('Pressure (kPa)')
axs[1, 1].set_ylabel('Specific Entropy (kJ/(kg*K))')

plt.tight_layout(rect=[0, 0, 1, 0.96]) 
plt.show()

### Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Example data or function for specific volume of saturated liquid
def specific_volume_saturated_liquid(p):
    # Replace with actual data or function
    return np.ones_like(p) * 0.001  # Placeholder data;

# Pressure range
pressure_range = np.linspace(300, 1500, 100)

# Create a subplot
fig, ax = plt.subplots(figsize=(8, 6))
ax.plot(pressure_range, specific_volume_saturated_liquid(pressure_range), marker='o', label='Saturated Liquid')
ax.set_title('Specific Volume of Saturated Liquid vs Pressure')
ax.set_xlabel('Pressure (kPa)')
ax.set_ylabel('Specific Volume (m³/kg)')
ax.legend()
ax.grid(True)

plt.show()


# Section 4 : Conclusion

*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*