# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  if len(A[0])==len(B):
    return 1
  else:
    return 0

##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
  x=np.zeros((len(A),len(B[0])),dtype=np.int64)
    for i in range(len(A)):
      for j in range(len(B[0])):
          for k in range(len(B)):
            x[i][j] += A[i][k] * B[k][j]
  return x

##### (iii) Using numpy

In [ ]:
def matrix_multiply_2(A,B):
  x=np.matmul(A,B)
  return x

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
  u=sum(x)/len(x)
  return u

In [ ]:
def standard_deviation(x):
  u=mean(x)
  f=0
  for i in range(len(x)):
    f+=(x[i]-u)*(x[i]-u)
  v=f/len(x)
  import math
  sd=pow(v,0.5)
  return sd

In [ ]:
def zscore_normalisation(x):
  zsn=np.zeros(len(x))
    for i in range(len(x)):
      zsn[i]=(x[i]-mean(x))/standard_deviation(x)
  return zsn

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
  zsn=np.zeros(len(x))
    for i in range(len(x)):
      zsn[i]=(x[i]-np.mean(x))/np.std(x)
  return zsn

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
  s=1/(1+np.exp(-x))
  return s

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
  d=(sigmoidfn(x))*(1-sigmoidfn(x))
  return d

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [ ]:
df=pd.read_csv("superheated_vapor_properties.csv")


### Display the shape of data frame


In [ ]:
df.shape

### Return an array containing names of all the columns

In [ ]:
df.columns

### Display the number of null values in each column of the dataframe



In [ ]:
df.isnull().sum()

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
df["Property_at_pressure"]=0
for i in range(len(df)):
    df["Property_at_pressure"][i]=str(df['Property'][i])+" at "+str((df['Pressure'][i]))
df.head()
for i in range(len(df)):
    if df["Property_at_pressure"][i]=="H at 75.0":
        print("Enthalpy at 75 kPa and 573K is",df["300"][i])
for i in range(len(df)):
    if df["Property_at_pressure"][i]=="S at 250.0":
        print("Entropy at 250 kPa and 493K is",df["220"][i])

### Find out the column with the highest number of missing values

In [ ]:
df.isnull().sum().idxmax()

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
df[(df['Property']=='H')]['Liq_Sat'].mean()

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
V_data=df[(df['Property']=='V')]
U_data=df[(df['Property']=='U')]
H_data=df[(df['Property']=='H')]
S_data=df[(df['Property']=='S')]

# Section 3: Plotting with Matplotlib

### Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
plt.subplot(3,3,1)
plt.plot(V_data['Pressure'],V_data['Liq_Sat'],'g.')
plt.xlabel("Pressure")
plt.ylabel("V")
plt.title("V_sat_liq")  
plt.subplot(3,3,3)
plt.plot(U_data['Pressure'],U_data['Liq_Sat'],'b.')
plt.xlabel("Pressure")
plt.ylabel("U")
plt.title("U_sat_liq")
plt.subplot(3,3,7)
plt.plot(H_data['Pressure'],H_data['Liq_Sat'],'r.')
plt.xlabel("Pressure")
plt.ylabel("H")
plt.title("H_sat_liq")
plt.subplot(3,3,9)
plt.plot(S_data['Pressure'],S_data['Liq_Sat'],'y.')
plt.xlabel("Pressure")
plt.ylabel("S")
plt.title("S_sat_liq")

### Plot the same for saturated vapor.

In [ ]:
plt.subplot(3,3,1)
plt.plot(V_data['Pressure'],V_data['Vap_Sat'],'g.')
plt.xlabel("Pressure")
plt.ylabel("V")
plt.title("V_sat_Vap")  
plt.subplot(3,3,3)
plt.plot(U_data['Pressure'],U_data['Vap_Sat'],'b.')
plt.xlabel("Pressure")
plt.ylabel("U")
plt.title("U_sat_Vap")
plt.subplot(3,3,7)
plt.plot(H_data['Pressure'],H_data['Vap_Sat'],'r.')
plt.xlabel("Pressure")
plt.ylabel("H")
plt.title("H_sat_Vap")
plt.subplot(3,3,9)
plt.plot(S_data['Pressure'],S_data['Vap_Sat'],'y.')
plt.xlabel("Pressure")
plt.ylabel("S")
plt.title("S_sat_Vap")

### Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
plt.plot(V_data['Pressure'],V_data['Liq_Sat'],'go')
plt.xlabel("Pressure")
plt.ylabel("V")
plt.title("V_sat_Liq")
plt.xlim([300,1500])
plt.show()

# Section 4 : Conclusion

*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*