# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
#your code here
import numpy as np
import pandas as pd
from matplotlib import pyplot 
import math

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  #your code here
  if len(A[0]) == len(B):
     return True
  else:
     return False


##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
    #your code here
    a = []
    for x in A:
        a.append(list(x))
    b = []
    for y in B:
        b.append(list(y))
    prod = []
    for i in range(len(a)):
        prod.append([])
        for j in range(len(b[0])):
            s=0
            for k in range(len(a[0])):
                s+=a[i][k]*b[k][j]
            prod[i]+=[s,]
    return np.array(prod)

##### (iii) Using numpy

In [ ]:
def matrix_multiply_2(A,B):
  #your code here
  np.matmul(A,B)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
    #your code here
    # a,b is the size of the matrix
    s = 0
    if type(x[0]) != list:
        a,b = 1, len(x)
        s = sum(x)
    else:
        a,b = len(x[0]), len(x)
        for i in range(b):
            for k in x[i] :
                s+=k
    return s/(a*b)

In [ ]:
def standard_deviation(x):
    #your code here
    #root of avg of sum of squares of deviation
    ss = 0
    x_ = mean(x)
    if type(x[0]) != list:
        a,b = 1, len(x)
        for i in range(b):
            ss += (x_ - x[i])**2
    else:
        a,b = len(x[0]), len(x)
        for i in range(b):
            for k in x[i] :
                ss +=(x_ - k)**2
    return (ss/(a*b))**(1/2)


In [ ]:
def zscore_normalisation(x):
    #your code here
    # (x-mean)/std
    x_ = mean(x)
    xstd = standard_deviation(x)
    if type(x[0]) != list:
        a,b = 1, len(x)
        y=[]
        for i in range(b):
            y.append(0)
        for i in range(b):
            try:
                y[i] = (x[i] - x_)/xstd
            except(ZeroDivisionError):
                y[i]=0
    else:
        a,b = len(x[0]), len(x)
        y=[]
        dummy = []
        for i in range(a):
            dummy.append(0)
        for _ in range(b):
            y.append(list(dummy))
        for i in range(b):
            for j in range(len(x[i])):
                y[i][j] =(x[i][j] - x_)/xstd
    return y


##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
    #your code here
    x = np.array(x)
    x = (x - x.mean())/x.std()
    a = []
    try: 
        for k in list(x):
            a.append(list(k))
    except(TypeError):
        a = list(x)
    return a
    

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
  #your code here
    g = 1/(1+ math.exp(-x))
    return g


##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
  #your code here
    g_ = math.exp(-x)/(1+ math.exp(-x))**2
    return g_

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [ ]:
#your code here
svp = pd.read_csv("superheated_vapor_properties.csv")

### Display the shape of data frame


In [ ]:
#your code here
print(svp.shape)

### Return an array containing names of all the columns

In [ ]:
#your code here
print(svp.columns)

### Display the number of null values in each column of the dataframe



In [ ]:
#your code here
mv = svp.isnull().sum()
print(mv)

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
#your code here
svp["Property at Pressure"] = svp['Property'] + ' at ' + ((svp['Pressure'])).astype(int).astype(str) 
enthalpy = svp.loc[svp["Property at Pressure"]=='H at 75']['300']
print(enthalpy.values[0])
entropy = svp.loc[svp["Pressure"]==250]['220']
print(entropy.values[0])

### Find out the column with the highest number of missing values

In [ ]:
#your code here

m = mv.max()
c = dict(mv.eq(m))
col = ''
for a in c:
  if c[a]:
    col = a
print(col)

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
#your code here
avg_enthalpy = svp.loc[svp["Property"]=='H']["Liq_Sat"].mean()
print(avg_enthalpy)

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here
Vdat = svp.loc[svp["Property"]=='V']
Vdat.to_csv("V_data")
Udat = svp.loc[svp["Property"]=='U']
Udat.to_csv("U_data")
Hdat = svp.loc[svp["Property"]=='H']
Hdat.to_csv("H_data")
Sdat = svp.loc[svp["Property"]=='S']
Sdat.to_csv("S_data")

# Section 3: Plotting with Matplotlib

### Plot the properties (specific volume, specific internal energy, specific enthalpy, specific entropy) vs Pressure for saturated liquid.

Note:
- Try using the subplot feature of matplotlib(Explore it!!)
- Provide appropriate title, labels, markersize and other parameters to the plot

In [ ]:
#your code here
plt.subplot(1, 4, 1)
plt.scatter(Vdat["Pressure"], Vdat["Liq_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Volume")
plt.subplot(1, 4, 2)
plt.scatter(Udat["Pressure"], Udat["Liq_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Energy")
plt.subplot(1, 4, 3)
plt.scatter(Hdat["Pressure"], Hdat["Liq_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Enthalpy")
plt.subplot(1, 4, 4)
plt.scatter(Sdat["Pressure"], Sdat["Liq_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Entropy")
plt.suptitle("Pressure v/s Property")
plt.tight_layout()
plt.show()

### Plot the same for saturated vapor.

In [ ]:
#your code here
plt.subplot(1, 4, 1)
plt.scatter(Vdat["Pressure"], Vdat["Vap_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Volume")
plt.subplot(1, 4, 2)
plt.scatter(Udat["Pressure"], Udat["Vap_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Energy")
plt.subplot(1, 4, 3)
plt.scatter(Hdat["Pressure"], Hdat["Vap_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Enthalpy")
plt.subplot(1, 4, 4)
plt.scatter(Sdat["Pressure"], Sdat["Vap_Sat"],s=5)
plt.xlabel("Pressure")
plt.ylabel("Specific Entropy")
plt.suptitle("Pressure v/s Property")
plt.tight_layout()
plt.show()

### Plot the specific volume of saturated liquid between 300 kPa and 1500 kPa

In [ ]:
#your code here
plt.scatter(((Vdat["Pressure"]>=300) & (Vdat["Pressure"]<=1500)), Vdat["Liq_Sat"],s=5)
plt.title("Pressure v/s Specific Volume of a Saturated Liquid")
plt.xlabel("Pressure")
plt.ylabel("Specific Volume")
plt.show()

# Section 4 : Conclusion

*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*